config/routes.rb
ProjetoBd::Application.routes.draw do
  get "relatorios/index"
  resources :solicitacoes

  resources :compra_produtos

  resources :producoes

  resources :produtos

  resources :compra_materias_primas

  resources :materias_primas

  resources :fornecedores

  resources :funcionarios

  resources :pessoas

  resources :telefones

  resources :enderecos

  resources :user_sessions

  resources :home

  resources :relatorios

  match 'login' => "user_sessions#new",      :as => :login,   via: [:get, :post]
  match 'logout' => "user_sessions#destroy", :as => :logout,  via: [:get, :post]

  get 'fornecedores/:id/historico' => 'fornecedores#historico', as: 'historico_fornecedor'

  get 'pessoas/:id/historico' => 'pessoas#historico', as: 'historico_cliente'

  resource :users
  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup,              via: [:get, :post]
	
	root :to => "user_sessions#new"
  

end

app/models/compra_produto.rb
class CompraProduto < ActiveRecord::Base
	belongs_to :fornecedor

	has_many :produto_comprados
	has_many :produtos, :through => :produto_comprados
	accepts_nested_attributes_for :produto_comprados, :allow_destroy => true
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
	belongs_to :enderecavel, :polymorphic => true
end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
	has_one :endereco, :as => :enderecavel, :dependent => :destroy
	accepts_nested_attributes_for :endereco, :allow_destroy => true
	
	has_one :telefone, :as => :telefonavel, :dependent => :destroy
	accepts_nested_attributes_for :telefone, :allow_destroy => true
	
	has_many :compra_produtos
	accepts_nested_attributes_for :compra_produtos

	has_many :compra_materias_primas
	accepts_nested_attributes_for :compra_materias_primas

	def self.search(search, id)
		if search
			where(['nome LIKE ? OR cnpj LIKE ?', "%#{search}%", "%#{search}%"])
		else
			scoped
		end
	end
end

app/models/funcionario.rb
class Funcionario < Pessoa
	self.table_name = "funcionarios"
end

app/models/materia_comprada.rb
class MateriaComprada < ActiveRecord::Base
	belongs_to :materia_prima
	belongs_to :compra_materia_prima
	accepts_nested_attributes_for :materia_prima
end

app/models/materia_prima.rb
class MateriaPrima < ActiveRecord::Base
	has_many :materia_utilizadas
	has_many :producoes, :through => :materia_utilizadas
	accepts_nested_attributes_for :producoes

	has_many :materia_compradas
	has_many :compra_materias_primas, :through => :materia_compradas
	accepts_nested_attributes_for :compra_materias_primas

	def self.search(search, id)
		if search
			where(['nome LIKE ? OR codigo LIKE ?', "%#{search}%", "%#{search}%"])
		else
			scoped
		end
	end
end

app/models/materia_utilizada.rb
class MateriaUtilizada < ActiveRecord::Base
	belongs_to :materia_prima
	belongs_to :producao
	accepts_nested_attributes_for :materia_prima
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
	has_one :endereco, :as => :enderecavel, :dependent => :destroy
	accepts_nested_attributes_for :endereco, :allow_destroy => true
	
	has_one :telefone, :as => :telefonavel, :dependent => :destroy
	accepts_nested_attributes_for :telefone, :allow_destroy => true
	
	has_many :solicitacoes
	accepts_nested_attributes_for :solicitacoes

	def self.search(search, id)
		if search
			where(['nome LIKE ? OR cadastro LIKE ?', "%#{search}%", "%#{search}%"])
		else
			scoped
		end
	end
end

app/models/producao.rb
class Producao < ActiveRecord::Base
	belongs_to :produto

	has_many :materia_utilizadas
	has_many :materia_prima, :through => :materia_utilizadas
	accepts_nested_attributes_for :materia_utilizadas, :allow_destroy => true
end

app/models/produto.rb
class Produto < ActiveRecord::Base
	has_many :producoes
	accepts_nested_attributes_for :producoes

	has_many :produto_comprados
	has_many :compra_produtos, :through => :produto_comprados
	accepts_nested_attributes_for :compra_produtos

	has_many :produto_solicitados
	has_many :solicitacoes, :through => :produto_solicitados
	accepts_nested_attributes_for :solicitacoes

	def self.search(search, id)
		if search
			where(['nome LIKE ? OR codigo LIKE ?', "%#{search}%", "%#{search}%"])
		else
			scoped
		end
	end
end

app/models/produto_comprado.rb
class ProdutoComprado < ActiveRecord::Base
	belongs_to :produto
	belongs_to :compra_produto
	accepts_nested_attributes_for :produto
end

app/models/solicitacao.rb
class Solicitacao < ActiveRecord::Base
	belongs_to :pessoa

	has_many :produto_solicitados
	has_many :produtos, :through => :produto_solicitados
	accepts_nested_attributes_for :produto_solicitados, :allow_destroy => true

	def self.search(search, id)
		if search
   			begin_date = Date.new search["begin_date(1i)"].to_i, search["begin_date(2i)"].to_i, search["begin_date(3i)"].to_i
   			end_date = Date.new search["end_date(1i)"].to_i, search["end_date(2i)"].to_i, search["end_date(3i)"].to_i
			where(:data => begin_date..end_date)
		else
			scoped
		end
	end
end

app/models/telefone.rb
class Telefone < ActiveRecord::Base
	belongs_to :telefonavel, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_authentic do |c|
		c.login_field = 'email'
  	end # block optional

	def self.search(search, id)
		if search
			where(['nome LIKE ?', "%#{search}%"])
		else
			scoped
		end
	end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/compra_produtos_controller.rb
class CompraProdutosController < ApplicationController
  before_filter :require_user
  before_action :set_compra_produto, only: [:show, :edit, :update, :destroy]

  # GET /compra_produtos
  # GET /compra_produtos.json
  def index
    @compra_produtos = CompraProduto.all
  end

  # GET /compra_produtos/1
  # GET /compra_produtos/1.json
  def show
  end

  # GET /compra_produtos/new
  def new
    @compra_produto = CompraProduto.new
  end

  # GET /compra_produtos/1/edit
  def edit
  end

  # POST /compra_produtos
  # POST /compra_produtos.json
  def create
    @compra_produto = CompraProduto.new(compra_produto_params)

    respond_to do |format|
      if @compra_produto.save
        @compra_produto.produto_comprados.each do |item|
          i = Produto.find(item.produto_id)
          i.quantidade = i.quantidade + item.quantidade
          i.save
        end
        format.html { redirect_to @compra_produto, notice: 'Compra produto was successfully created.' }
        format.json { render action: 'show', status: :created, location: @compra_produto }
      else
        format.html { render action: 'new' }
        format.json { render json: @compra_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compra_produtos/1
  # PATCH/PUT /compra_produtos/1.json
  def update
    respond_to do |format|
      if @compra_produto.update(compra_produto_params)
        format.html { redirect_to @compra_produto, notice: 'Compra produto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @compra_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compra_produtos/1
  # DELETE /compra_produtos/1.json
  def destroy
    @compra_produto.produto_comprados.each do |item|
      i = Produto.find(item.produto_id)
      i.quantidade = i.quantidade - item.quantidade
      i.save
    end
    @compra_produto.destroy
    respond_to do |format|
      format.html { redirect_to compra_produtos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra_produto
      @compra_produto = CompraProduto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_produto_params
      params.require(:compra_produto).permit(:data, :status, :pagamento, :fornecedor_id, :produto_comprados_attributes => [:id, :quantidade, :_destroy, :produto_id])
    end
end

app/helpers/compra_produtos_helper.rb
module CompraProdutosHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/producoes_helper.rb
module ProducoesHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/compra_produtos/_form.html.erb
<%= simple_form_for(@compra_produto) do |f| %>
  <% if @compra_produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compra_produto.errors.count, "error") %> prohibited this compra_produto from being saved:</h2>

      <ul>
      <% @compra_produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.input :data %><br>

    <%= f.input :status %><br>

    <%= f.input :pagamento %><br>


  <%= f.association :fornecedor, :label_method => lambda { |fornecedor| "#{fornecedor.nome}" }%>
 
   
  <fieldset id="produtos"> 
    <ol> 
      <%= f.fields_for :produto_comprados do |ff| %>
      <%= ff.input :quantidade %>
      <%= ff.association :produto, label_method: :nome, value_method: :id, include_blank: false %>

      <%= link_to_remove_association "remove", ff%>
      <% end %>
    </ol>
      <%= link_to_add_association 'Adicionar produto', f, :produto_comprados, 'data-association-insertion-node' => "#produtos ol", 'data-association-insertion-method' => "append"%> 
  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compra_produtos/_materia_utilizada_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls">
	<%= f.input :quantidade %>
	<%= f.association :materia_prima, label_method: :nome, value_method: :id, include_blank: false %>

	<%= link_to_remove_association "remove", f%>
 </div>
</li>

app/views/compra_produtos/_produto_comprado_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls">
	<%= f.input :quantidade %>
	<%= f.association :produto, label_method: :nome, value_method: :id, include_blank: false %>

	<%= link_to_remove_association "remove", f%>
 </div>
</li>

app/views/compra_produtos/edit.html.erb
<h1>Compra de Produtos</h1>

<%= render 'form' %>

<%= link_to 'Detalhes', @compra_produto %> |
<%= link_to 'Voltar', compra_produtos_path %>

app/views/compra_produtos/index.html.erb
<div class="conteudo">

<h1>Compra de Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Status</th>
      <th>Pagamento</th>
      <th>Fornecedor</th>
      <th>Itens/Quantidades<th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @compra_produtos.each do |compra_produto| %>
      <tr>
        <td><%= compra_produto.data %></td>
        <td><%= compra_produto.status %></td>
        <td><%= compra_produto.pagamento %></td>
        <td><%= compra_produto.fornecedor.nome %></td>
        <td>
          <% compra_produto.produto_comprados.each do |produto_comprado| %>
          <%= produto_comprado.produto.nome %>/<%= produto_comprado.quantidade %>, 
          <% end %>
        </td>
        <td><%= link_to 'Detalhes', compra_produto %></td>
        <td><%= link_to 'Editar', edit_compra_produto_path(compra_produto) %></td>
        <td><%= link_to 'Apagar', compra_produto, method: :delete, data: { confirm: 'Certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Compra de Produto', new_compra_produto_path %>
</div>

app/views/compra_produtos/new.html.erb
<h1>Nova Compra de Produtos</h1>

<%= render 'form' %>

<%= link_to 'Voltar', compra_produtos_path %>

app/views/compra_produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @compra_produto.data %>
</p>

<p>
  <strong>Status:</strong>
  <%= @compra_produto.status %>
</p>

<p>
  <strong>Pagamento:</strong>
  <%= @compra_produto.pagamento %>
</p>

<p>
  <strong>Fornecedor:</strong>
  <%= @compra_produto.fornecedor.nome %>
</p>

<p>


</p>
	<strong>Itens/Quantidades:</strong> 
	<% @compra_produto.produto_comprados.each do |produto_comprado| %>
    	<%= produto_comprado.produto.nome %>/<%= produto_comprado.quantidade %>, 
    <% end %>

<%= link_to 'Editar', edit_compra_produto_path(@compra_produto) %> |
<%= link_to 'Voltar', compra_produtos_path %>