config/routes.rb
ProjetoBd::Application.routes.draw do
  get "relatorios/index"
  resources :solicitacoes

  resources :compra_produtos

  resources :producoes

  resources :produtos

  resources :compra_materias_primas

  resources :materias_primas

  resources :fornecedores

  resources :funcionarios

  resources :pessoas

  resources :telefones

  resources :enderecos

  resources :user_sessions

  resources :home

  resources :relatorios

  match 'login' => "user_sessions#new",      :as => :login,   via: [:get, :post]
  match 'logout' => "user_sessions#destroy", :as => :logout,  via: [:get, :post]

  get 'fornecedores/:id/historico' => 'fornecedores#historico', as: 'historico_fornecedor'

  get 'pessoas/:id/historico' => 'pessoas#historico', as: 'historico_cliente'

  resource :users
  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup,              via: [:get, :post]
	
	root :to => "user_sessions#new"
  

end

app/models/compra_produto.rb
class CompraProduto < ActiveRecord::Base
	belongs_to :fornecedor

	has_many :produto_comprados
	has_many :produtos, :through => :produto_comprados
	accepts_nested_attributes_for :produto_comprados, :allow_destroy => true
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
	belongs_to :enderecavel, :polymorphic => true
end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
	has_one :endereco, :as => :enderecavel, :dependent => :destroy
	accepts_nested_attributes_for :endereco, :allow_destroy => true
	
	has_one :telefone, :as => :telefonavel, :dependent => :destroy
	accepts_nested_attributes_for :telefone, :allow_destroy => true
	
	has_many :compra_produtos
	accepts_nested_attributes_for :compra_produtos

	has_many :compra_materias_primas
	accepts_nested_attributes_for :compra_materias_primas

	def self.search(search, id)
		if search
			where(['nome LIKE ? OR cnpj LIKE ?', "%#{search}%", "%#{search}%"])
		else
			scoped
		end
	end
end

app/models/funcionario.rb
class Funcionario < Pessoa
	self.table_name = "funcionarios"
end

app/models/materia_comprada.rb
class MateriaComprada < ActiveRecord::Base
	belongs_to :materia_prima
	belongs_to :compra_materia_prima
	accepts_nested_attributes_for :materia_prima
end

app/models/materia_prima.rb
class MateriaPrima < ActiveRecord::Base
	has_many :materia_utilizadas
	has_many :producoes, :through => :materia_utilizadas
	accepts_nested_attributes_for :producoes

	has_many :materia_compradas
	has_many :compra_materias_primas, :through => :materia_compradas
	accepts_nested_attributes_for :compra_materias_primas

	def self.search(search, id)
		if search
			where(['nome LIKE ? OR codigo LIKE ?', "%#{search}%", "%#{search}%"])
		else
			scoped
		end
	end
end

app/models/materia_utilizada.rb
class MateriaUtilizada < ActiveRecord::Base
	belongs_to :materia_prima
	belongs_to :producao
	accepts_nested_attributes_for :materia_prima
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
	has_one :endereco, :as => :enderecavel, :dependent => :destroy
	accepts_nested_attributes_for :endereco, :allow_destroy => true
	
	has_one :telefone, :as => :telefonavel, :dependent => :destroy
	accepts_nested_attributes_for :telefone, :allow_destroy => true
	
	has_many :solicitacoes
	accepts_nested_attributes_for :solicitacoes

	def self.search(search, id)
		if search
			where(['nome LIKE ? OR cadastro LIKE ?', "%#{search}%", "%#{search}%"])
		else
			scoped
		end
	end
end

app/models/producao.rb
class Producao < ActiveRecord::Base
	belongs_to :produto

	has_many :materia_utilizadas
	has_many :materia_prima, :through => :materia_utilizadas
	accepts_nested_attributes_for :materia_utilizadas, :allow_destroy => true
end

app/models/produto.rb
class Produto < ActiveRecord::Base
	has_many :producoes
	accepts_nested_attributes_for :producoes

	has_many :produto_comprados
	has_many :compra_produtos, :through => :produto_comprados
	accepts_nested_attributes_for :compra_produtos

	has_many :produto_solicitados
	has_many :solicitacoes, :through => :produto_solicitados
	accepts_nested_attributes_for :solicitacoes

	def self.search(search, id)
		if search
			where(['nome LIKE ? OR codigo LIKE ?', "%#{search}%", "%#{search}%"])
		else
			scoped
		end
	end
end

app/models/produto_comprado.rb
class ProdutoComprado < ActiveRecord::Base
	belongs_to :produto
	belongs_to :compra_produto
	accepts_nested_attributes_for :produto
end

app/models/solicitacao.rb
class Solicitacao < ActiveRecord::Base
	belongs_to :pessoa

	has_many :produto_solicitados
	has_many :produtos, :through => :produto_solicitados
	accepts_nested_attributes_for :produto_solicitados, :allow_destroy => true

	def self.search(search, id)
		if search
   			begin_date = Date.new search["begin_date(1i)"].to_i, search["begin_date(2i)"].to_i, search["begin_date(3i)"].to_i
   			end_date = Date.new search["end_date(1i)"].to_i, search["end_date(2i)"].to_i, search["end_date(3i)"].to_i
			where(:data => begin_date..end_date)
		else
			scoped
		end
	end
end

app/models/telefone.rb
class Telefone < ActiveRecord::Base
	belongs_to :telefonavel, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_authentic do |c|
		c.login_field = 'email'
  	end # block optional

	def self.search(search, id)
		if search
			where(['nome LIKE ?', "%#{search}%"])
		else
			scoped
		end
	end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_filter :require_user
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.search(params[:search], params[:id])
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
    endereco = @funcionario.build_endereco
    telefone = @funcionario.build_telefone
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render action: 'show', status: :created, location: @funcionario }
      else
        format.html { render action: 'new' }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :cadastro, :email, :cargo, :senha, endereco_attributes: [:id, :bairro, :cep, :cidade, :logradouro, :complemento, :estado, :numero], telefone_attributes: [:id, :ddd, :numero])
    end
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/producoes_helper.rb
module ProducoesHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/funcionarios/_endereco_fields.html.erb
<p>
  <%= f.label :bairro, "Bairro" %></br>
  <%= f.text_field :bairro %></br>
  <%= f.label :cep, "CEP" %></br>
  <%= f.text_field :cep %></br>
  <%= f.label :cidade, "Cidade" %></br>
  <%= f.text_field :cidade %></br>
  <%= f.label :logradouro, "Logradouro" %></br>
  <%= f.text_field :logradouro %></br>
  <%= f.label :complemento, "Complemento" %></br>
  <%= f.text_field :complemento %></br>
  <%= f.label :estado, "Estado" %></br>
  <%= f.text_field :estado %></br>
  <%= f.label :numero, "Número" %></br>
  <%= f.text_field :numero %>
</p>

app/views/funcionarios/_form.html.erb
<%= form_for [@enderecavel, @telefonavel, @funcionario] do |f| %>
  <% if @funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% @funcionario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cadastro %><br>
    <%= f.text_field :cadastro %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cargo %><br>
    <%= f.text_field :cargo %>
  </div>
  <div class="field">
    <%= f.label :senha %><br>
    <%= f.text_field :senha %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.fields_for :endereco do |builder| %>
      <%= render "endereco_fields", :f => builder %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.fields_for :telefone do |builder| %>
      <%= render "telefone_fields", :f => builder %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/funcionarios/_telefone_fields.html.erb
<p>
  <%= f.label :ddd, "DDD" %></br>
  <%= f.text_field :ddd %></br>
  <%= f.label :numero,"Número" %></br>
  <%= f.text_field :numero %>
</p>

app/views/funcionarios/edit.html.erb
<h1>Funcionário</h1>

<%= render 'form' %>

<%= link_to 'Detalhes', @funcionario %> |
<%= link_to 'Voltar', funcionarios_path %>

app/views/funcionarios/index.html.erb
<div class="conteudo">
<h1>Funcionarios</h1>

<div class="data">
<!--Form de busca-->
<%= form_tag funcionarios_path, :method => 'get'  do %>
   <%= text_field_tag :search, params[:search]%>
   <%= submit_tag "Buscar", :nome => nil  %>
 <% end %>
<!--/Form de busca-->
</div>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cadastro</th>
      <th>Email</th>
      <th>Cargo</th>
      <th>Senha</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.cadastro %></td>
        <td><%= funcionario.email %></td>
        <td><%= funcionario.cargo %></td>
        <td><%= funcionario.senha %></td>
        <td><%= link_to 'Detalhes', funcionario %></td>
        <td><%= link_to 'Edit', edit_funcionario_path(funcionario) %></td>
        <td><%= link_to 'Destroy', funcionario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Funcionario', new_funcionario_path %>
<div>

app/views/funcionarios/new.html.erb
<h1>Novo Funcionário</h1>

<%= render 'form' %>

<%= link_to 'Voltar', funcionarios_path %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Cadastro:</strong>
  <%= @funcionario.cadastro %>
</p>

<p>
  <strong>Email:</strong>
  <%= @funcionario.email %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @funcionario.cargo %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @funcionario.senha %>
</p>

<%= link_to 'Editar', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Voltar', funcionarios_path %>